# enabled: true or false to disable the plugin
enabled: true

# Sitemap plugin priority
priority: 95

# Route
route: sitemap.xml

# Ignore list
ignore:

# Addition list
additions:

# Default values for entries
default:
  changefreq: daily
  priority: !!float 1
